name: OpenSourceProject_NaveenM Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Builds the OpenSourceProject Docker image
      run: docker build . --file Dockerfile --tag thehilifer/naveen_fast_api_docker_up:$(date +%s)
